version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dup
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    ports: ["9000:9000","9001:9001"]
    volumes: ["./.data/minio:/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 30

  createbucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      mc alias set local http://minio:9000 ${S3_ACCESS_KEY:-minioadmin} ${S3_SECRET_KEY:-minioadmin} &&
      mc mb -p local/${S3_BUCKET:-dups} || true

  rclone:
    image: rclone/rclone:latest
    command: >
      rcd --rc-addr :5572 --rc-user ${RCLONE_RC_USER:-rclone} --rc-pass ${RCLONE_RC_PASS:-rclone}
      --rc-web-gui --rc-web-gui-no-open-browser
    ports: ["5572:5572"]
    volumes:
      - ./.data/rclone:/config
      - ./.data/rclone-cache:/cache
    depends_on:
      - minio

  web:
    build: ./apps/web
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dup
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_BUCKET: ${S3_BUCKET:-dups}
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-devsecret}
      EMAIL_FROM: login@dupli.clean
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      RCLONE_RC_URL: http://rclone:5572
      RCLONE_RC_USER: ${RCLONE_RC_USER:-rclone}
      RCLONE_RC_PASS: ${RCLONE_RC_PASS:-rclone}
      NEXT_PUBLIC_S3_URL: http://localhost:9000/dups
    ports: ["3000:3000"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 10s
      timeout: 5s
      retries: 30

  worker:
    build: ./apps/worker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dup
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
      S3_BUCKET: ${S3_BUCKET:-dups}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
